"""Add is_available column

Revision ID: 6356228f5178
Revises: ba5641757d8b
Create Date: 2025-10-19 19:10:58.480323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6356228f5178'
down_revision = 'ba5641757d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
