"""create all tables

Revision ID: ba5641757d8b
Revises: 
Create Date: 2025-10-17 12:01:28.544794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5641757d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mdeicine_commitment', sa.VARCHAR(length=100), nullable=True),
    sa.Column('high_irritability_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('clam_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('activity_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('comfortsble_activity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_register.doctor_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###
