"""add day_of_week and time nullable

Revision ID: d019915487ab
Revises: 6356228f5178
Create Date: 2025-10-22 21:41:51.534520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd019915487ab'
down_revision = '6356228f5178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_doctor_appointment')
    with op.batch_alter_table('doctor_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=10), nullable=True))
        batch_op.drop_column('appointment_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('time')
        batch_op.drop_column('day_of_week')

    op.create_table('_alembic_tmp_doctor_appointment',
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('day_of_week', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_register.doctor_id'], ),
    sa.PrimaryKeyConstraint('appointment_id'),
    sa.UniqueConstraint('appointment_id')
    )
    # ### end Alembic commands ###
